<?php


namespace Source\Models;


/**
 * Class Configures
 * @package Source\Models
 */
class Configures extends Model
{

    /** @var Identificador da configure */
    private $id;

    /** @var Nome da configure */
    private $name;

    /** @var Valor da configure */
    private $value;

    /**
     * Configures constructor.
     */
    public function __construct()
    {
        parent::__construct("configures", ["name", "value"]);
    }

    /**
     * @param $name
     * @return string|null
     */
    public function __get($name)
    {
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    /**
     * @param $name
     * @param $value
     */
    public function __set($name, $value)
    {
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    /**
     *  Função responsavel por buscar cinfigures do banco de dados.
     *
     * @param string $name
     * @return array|null
     */
    public function getConfigure(string $name): ?\stdClass
    {
        $configure = $this->find("name = :name", "name={$name}")->fetch();

        $this->id = $configure->id;
        $this->name = $configure->name;
        $this->value = json_decode(utf8_encode($configure->value));

        return $this->value;
    }

    /**
     * @return array|null
     */
    public function getAllConfigures(): ?array
    {
        return $this->find()->order('name')->fetch(true);
    }
}