<?php

namespace Theme\Pages\Publication;

use Source\Controllers\Upload;
use Source\Models\Model;

class PublicationModel extends Model
{
    const IMAGES_FOLDER = ROOT . DS . 'theme' . DS . 'upload' . DS . 'publication' . DS;

    public function __construct()
    {
        $this->setTable("publications");

        parent::__construct("publications", ["title", "slug", "description"]);
    }

    public function destroy(): bool
    {
        if (file_exists(self::IMAGES_FOLDER . $this->image)) {
            Upload::fileDestroy(self::IMAGES_FOLDER . $this->image);
        }

        return parent::destroy(); // TODO: Change the autogenerated stub
    }
}
