<?php

    namespace Theme\Pages\Banner;

    use Source\Controllers\Upload;
    use Source\Models\Model;

    class BannerModel extends Model
    {
        const IMAGES_FOLDER = ROOT . DS . 'theme' . DS . 'upload' . DS . 'banner' . DS;

        public function __construct()
        {
            $this->setTable("banners");

            parent::__construct("banners", ["title", "slug", "description"]);
        }

        public function destroy(): bool
        {
            if (file_exists(self::IMAGES_FOLDER . $this->image)) {
                Upload::fileDestroy(self::IMAGES_FOLDER . $this->image);
            }

            return parent::destroy(); // TODO: Change the autogenerated stub
        }
    }